---
title: "plotly"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install and Load Packages



```{r cars}
##### Install and load packages
#install.packages("plotly")
#install.packages("tidyverse")
#install.packages("htmlwidgets")
library(plotly)
library(tidyverse)
library(htmlwidgets)

```

## Downloading Data


```{r pressure, echo=FALSE}
##### Import data

creatives <- read.csv(file="https://raw.githubusercontent.com/lgellis/MiscTutorial/master/ggplotly/Median_Earnings_of_Creative_Sector_Occupations__CLL.B.1.csv",
                      header=TRUE, sep=",", stringsAsFactors = FALSE)

dim(creatives)
summary(creatives)
str(creatives)
head(creatives)
```


## Format Data and create interactive scatterplot

```{r}
##### Data processing
#Rename the columns and create a new column for year over year change

creatives <- creatives %>% 
  rename(Median_2016 = X2016.Median.hourly.earnings, Median_2017 = X2017.Median.hourly.earnings) %>% 
  rowwise() %>% 
  mutate(Percent_Improvement = round((Median_2016-Median_2017)/Median_2016*100,2))


##### Create a scatterPlot

scatterPlot <- creatives %>% 
  ggplot(aes(x = Median_2017, y = Percent_Improvement)) + 
  geom_point(alpha=0.7, colour = "#51A0D5") + 
  labs(x = "Median Occupation Hourly Wage in 2017", 
       y = "% Improvement Year over Year (2016 to 2017)",
       title = "Austin Creative Occupations Median Hourly Wage") +
  geom_hline(yintercept=0, linetype="dashed", color = "#2C528C", size=0.5) +
  theme_classic()

ggplotly(scatterPlot)
```














